[Feature] core 서버에서 사용하는 엔티티를 설계했어요. (#4)
depromeet/13th-2team-backend pull request #5
Opened 2023-06-17 12:32 UTC by parkje0927

## ❗️관련 이슈번호
- Close #4 

## ⚙️ 어떤 기능을 개발했나요?
- core 서버에 필요한 entity, enum 을 설계했어요.

## 🙋🏻 어떤 부분에 집중하여 리뷰해야 할까요?
- 네이밍에 대해서 한번 살펴봐주세요. 노션 페이지에도 업데이트 해두었습니다.
- `nullable = false` 처리는 아래 경우를 제외하고 모두 설정해두었습니다.

> - 모든 엔티티에서의 imageUrl
> - 음료 엔티티에서의 calorie
> - 멤버 엔티티에서의 email

- 이 컬럼들의 경우에는 디폴트 이미지가 들어가는 경우도 있을 것 같고 이후 상황들을 고려하여 이렇게 설계했는데 변경이 필요하다면 코멘트 남겨주세요.
- `ddl-auto` 의 경우 설정 내용을 빠르게 확인해보기 위해 create 으로 해두었어요. 개발 과정에서는 변경이 필요할 것 같습니다.

## 📖 (Optional) 참고자료
- 참고자료는 아니지만, DB 구성은 admin 과 동일하게 3307 port 설정으로 해두었고 readme 문서에 작성해두었어요.

2023-06-18 00:20 UTC, soochangoforit commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/entity/DrinkBookmarkEntity.java
> +    @JoinColumn(name = "member_id", nullable = false)
외래키 연관 관계 같은 경우는 JPA에서 랜덤한 문자열로 제약 조건 이름을 갖게 되는데 저희가 직접 제어하면 어떨까요??

```suggestion
    @JoinColumn(name = "member_id", nullable = false,  foreignKey = @ForeignKey(name = "fk_drinkBookMark_to_member"))
```

2023-06-18 00:31 UTC, soochangoforit commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/entity/MemberEntity.java
> +    @Column(name = "gender", nullable = false)
제가 Oauth2를 생각했었을 땐 우선 카카오로 로그인으로 최초 회원가입을 시작합니다.
부가 정보를 나타내는 컬럼값들을 제외한 상태로 1차적으로 save 쿼리가 나갑니다.

최초 가입자가 화면에서 추가적인 정보인 성별, 무게, 키, 나이를 입력하게 되고 그 값에 따라서 권장 섭취량을 갖게 됩니다.
이러한 변경 내역을 Member Entity를 향해 update 합니다.

그러면 이러한 상황에서는 API가 2개가 나오지 않을까요??

로그인 API
추가정보 설정 API

그렇다면 위의 컬럼들은 nullable을 풀어야하지 않을까? 생각했어요

2023-06-18 06:03 UTC, soochangoforit commented on oversweet-api/build.gradle
> +    implementation 'mysql:mysql-connector-java:8.0.33'
해당 의존성은 oversweet-api 에 위치하는 것보단, oversweet-domain 영역에 넣는 건 어떻게 생각해요?

2023-06-18 12:20 UTC, parkje0927 commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/entity/DrinkBookmarkEntity.java
> +    @JoinColumn(name = "member_id", nullable = false)
이 부분은 제가 다시 살펴보고 수정해두겠습니다. 감사합니다!

2023-06-18 12:28 UTC, parkje0927 commented on oversweet-api/build.gradle
> +    implementation 'mysql:mysql-connector-java:8.0.33'
음 저의 경우에는 api 서버에서 yml 파일을 통해 db 설정을 진행하다보니 이 곳에서 import 를 받아야 한다고 생각했어요.

2023-06-19 07:44 UTC, LeeJejune requested changes

2023-06-19 07:44 UTC, LeeJejune commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/entity/RecordEntity.java
> +import jakarta.persistence.*;
import 할 때 * 쓰는거 주의해주세요

2023-06-19 07:44 UTC, LeeJejune commented on oversweet-api/build.gradle
> +    implementation 'mysql:mysql-connector-java:8.0.33'
implementation mysql:mysql-connector-java:8.0.33를 oversweet-domain으로 옮기시고, 아래처럼 domain 모듈을 가지고 오면 됩니다.

`implementation project(':oversweet-domain') 처럼 `

2023-06-19 07:51 UTC, LeeJejune commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/entity/MemberEntity.java
> +    private Integer weight;
개인적으로 궁금한건데 Integer 래퍼 클래스로 하신 이유가 있나요? null 처리 때문인가요??

2023-06-19 08:28 UTC, parkje0927 commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/entity/RecordEntity.java
> +import jakarta.persistence.*;
제준님 혹시 이 부분은 추가 설명 부탁드려도 될까요?
보통 저는 import, inline 정리 단축키를 많이 활용하는 편인데 * 을 쓰지 않으려면 import 정리 단축어 사용에 대해서도 고민을 해봐야할 것 같아서요!

2023-06-19 11:27 UTC, parkje0927 commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/entity/MemberEntity.java
> +    private Integer weight;
넵 고민하긴 했는데 null 처리 고려하여 래퍼 클래스로 했습니다.

2023-06-19 11:41 UTC, LeeJejune commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/entity/RecordEntity.java
> +import jakarta.persistence.*;
![image](https://github.com/depromeet/oversweet-core/assets/81547780/8c25d0c5-0ace-4292-ade9-9d8eb3689f0e)

위 9999 부분 설정해주면 되요!

2023-06-19 11:42 UTC, LeeJejune approved these changes

2023-06-19 11:51 UTC, parkje0927 commented on oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/entity/RecordEntity.java
> +import jakarta.persistence.*;
아하 오 저 몰랐어요!
감사합니다. 설정해서 수정할게요~

2023-06-20 12:55 UTC, merged